services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8080:8080
    environment:
      PORT: 8080
